### PR TITLE
Change the structure of the project so that tox can execute

### PR DESCRIPTION
**Pull request by bjcoleman**

### CODE REVIEW

**Comment by stevemac1900** [comment]
I don't know how much of a difference it makes, but this is all in your master branch

**Comment by stevemac1900** [comment]
Still need to make changes to test_size_filter and test_availability_filter to account for change in folder structure

**Comment by bjcoleman** [comment]
Weird, I had merge conflicts, but when I finished I didn't have those other files.  I added them, refactored, and got everything to pass the tests.

No, going from master isn't a problem - I should have used a branch, but that effects me, not the project.

**Comment by stevemac1900** [comment]
One more question, should we add tox to the requirements.txt?

**Comment by bjcoleman** [comment]
No, it has to be installed at the system level to work on the server.  You can actually run tox without creating the .env - that's basically what it does when you run tox.

**Comment by jpvonelli** [comment]
I would assume so yeah

**Pull request merged**
